### ISSUE TITLE
Optimize template and styles for Shadow DOM

### ISSUE THREAD

**Issue by justinfagnani** [rnglnd/htm-litelement#4]
It looks like the template and styles used in the LitElement version are still designed for global CSS. A couple of suggestions:

- Remove the `<div class="container">` element. With Shadow DOM it's unnecessary to have a containing element because the ShadowRoot itself is a container. The extra element just adds memory,  style resolution, layout, etc. costs.
- Remove unnecessary classes like `<h1 class="header">`. Because styles are scoped you don't need to be defensive with classes to avoid collisions. The `<h1>` is the only instance of that tag in the ShadowRoot so you can select it with simply `h1 { ... }` instead of `.header { ... }`. It looks like you could drop most of the classes, especially if you use elements like `<main>` and `<section>` instead of `<div>`.
- Use inline stylesheets in `<style>`tags.
  - External styles loaded with `<link rel=stylesheet>` work, but I'd recommend against them because they can result in FOUC for the component while the stylesheet loads and preventing the browser from loading the stylesheet for every instance of the component requires sufficient cache expiry times.
  - Inline `<style>` tags are deduplicated by browsers based on them having identical text content.
  - There may be concern about long stylesheets obscuring the template, but I find that generally styles in ShadowRoots are much simpler, so their size is smaller...
  - In an upcoming version of LitElement we'll recommend defining styles in a static `styles` property so that we can use the new Constructible Stylesheets spec to reuse styles without parsing or creating `<style>` elements, for a nice performance boost.
- Abstract repeated structures into a function or component:

This structure:

```js
                `<div class="chips">
                  <h3 class="main-header">Chips</h3>
                  <ul class="main-list">
                    ${chipItems.map((item) => html`
                      <li class="main-item" @click=${() => this.addItem(item)}>
                        <span>${item.description}</span><span>£${item.price}</span>
                      </li>
                    `)}
                  </ul>
                </div>`
```

can be but into a method:
```js
renderSection(name, items) {
  return html`
    <section class="name">
      <h3 class="main-header">Chips</h3>
      <ul class="main-list">
        ${items.map((item) => html`
          <li class="main-item" @click=${() => this.addItem(item)}>
            <span>${item.description}</span><span>£${item.price}</span>
          </li>
        `)}
      </ul>
    </section>
  `;
}
```

Then used inline:

```js
            `<link rel="stylesheet" type="text/css" href="css/styles.css">
            <div class="container">
              <h1 class="header">
                Stevie's chippy
              </h1>
              <div class="main">
              ${this.renderSection('chips', chipItems)}
              ${this.renderSection('burgers', burgerItems)}`
```

**Comment by rnglnd** [comment]
Thanks for this issue, it has a ton of great information in it! I did want to look further into how to use global styles in lit-html (and I guess web components in general as this is really my first foray into them) further.

I only really saw good examples on scoped styles and I know that'll be the most common use case and, in general, I'm a fan. However, the purpose of this repo was to show a simple app using 2 different libraries built kind kind of the same way (relative to their features). So I didn't want to use scoped styles and change what I had in the htm app, I wanted to be able to have the same stylesheet and make use of it in both.

However, neither app is really done how I would actually do it in production so I do want to explore that and I had thought about refactoring both into smaller components and scoping styles in the web component. I still might do that but I think I'll create another repo and create everything as if it were a proper app, small components that can be shared, using the all the feature of both libraries etc.

So I will keep this issue open but I feel it might be closed by another repo as I want to bundle both of them like your average SPA so I can play about with performance etc and see what works best.

**Comment by rnglnd** [comment]
These concerns have been addressed in https://github.com/rnglnd/htm-litelement-extended. Leaving this example as is for the time being.
